# Generated by Django 4.0.2 on 2022-02-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_alter_exercise_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Upper Body', 'Upper Body'), ('Lower Body', 'Lower Body'), ('Full Body', 'Full Body')], max_length=16),
        ),
    ]
