# Generated by Django 3.2.5 on 2022-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_workout', models.IntegerField(default=0)),
                ('p_tabata', models.IntegerField(default=0)),
                ('p_memory', models.IntegerField(default=0)),
                ('p_speed', models.IntegerField(default=0)),
            ],
        ),
    ]
