# Generated by Django 3.2.5 on 2022-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.CharField(choices=[('EU', 'Europe'), ('AM', 'America'), ('AF', 'Africa'), ('AS', 'Asia'), ('OC', 'Oceania')], max_length=16),
        ),
    ]
