# Generated by Django 3.2.5 on 2022-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.CharField(choices=[('Europe', 'Europe'), ('America', 'America'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania')], max_length=16),
        ),
    ]
