# Generated by Django 3.2.5 on 2022-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220213_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Europe', 'Europe'), ('America', 'America'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania')], max_length=16)),
                ('points_workout', models.IntegerField(default=0)),
                ('points_tabata', models.IntegerField(default=0)),
                ('points_memory', models.IntegerField(default=0)),
                ('points_speed', models.IntegerField(default=0)),
            ],
        ),
    ]
