# Generated by Django 4.0.2 on 2022-02-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userexerciseslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExercisesList',
        ),
    ]
