# Generated by Django 3.2.5 on 2022-02-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card1',
            name='name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Card2',
        ),
    ]
