# Generated by Django 3.2.5 on 2022-02-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20220204_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card1',
            new_name='Card',
        ),
    ]
