# Generated by Django 3.2.5 on 2022-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_rename_card1_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='card_pics'),
        ),
    ]
