# Generated by Django 4.0.4 on 2022-06-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='card-pics'),
        ),
    ]
