# Generated by Django 4.0.4 on 2022-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_remove_card_image_card_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_name',
            field=models.CharField(default='<django.db.models.fields.charfield>.png', max_length=32),
        ),
    ]
