# Generated by Django 4.0.4 on 2022-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0009_card_image_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_n',
        ),
        migrations.AlterField(
            model_name='card',
            name='image_name',
            field=models.CharField(default='empty', max_length=32),
        ),
    ]
